apiVersion: v1
kind: PersistentVolume
metadata:
  name: api-tester-2121-files
  labels:
    part-of: k8s-anotherclass
    component: backend-server
    name: api-tester
    instance: api-tester-2121-files
    version: 1.0.0
    managed-by: kubectl
spec:
  capacity:
    storage: 2G
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  local:
    path: "/pvs/2121"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - {key: kubernetes.io/hostname, operator: In, values: [master-01]}
